package com.sample.dao.entity;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.ID
     *
     * @mbg.generated Wed Jul 12 19:44:04 JST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.NAME
     *
     * @mbg.generated Wed Jul 12 19:44:04 JST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.ADDRESS
     *
     * @mbg.generated Wed Jul 12 19:44:04 JST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.EMAIL
     *
     * @mbg.generated Wed Jul 12 19:44:04 JST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.MEMBERSHIP_TYPE
     *
     * @mbg.generated Wed Jul 12 19:44:04 JST 2017
     */
    private String membershipType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.GRADUATE
     *
     * @mbg.generated Wed Jul 12 19:44:04 JST 2017
     */
    private String graduate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.ID
     *
     * @return the value of CUSTOMER.ID
     *
     * @mbg.generated Wed Jul 12 19:44:04 JST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.ID
     *
     * @param id the value for CUSTOMER.ID
     *
     * @mbg.generated Wed Jul 12 19:44:04 JST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.NAME
     *
     * @return the value of CUSTOMER.NAME
     *
     * @mbg.generated Wed Jul 12 19:44:04 JST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.NAME
     *
     * @param name the value for CUSTOMER.NAME
     *
     * @mbg.generated Wed Jul 12 19:44:04 JST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.ADDRESS
     *
     * @return the value of CUSTOMER.ADDRESS
     *
     * @mbg.generated Wed Jul 12 19:44:04 JST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.ADDRESS
     *
     * @param address the value for CUSTOMER.ADDRESS
     *
     * @mbg.generated Wed Jul 12 19:44:04 JST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.EMAIL
     *
     * @return the value of CUSTOMER.EMAIL
     *
     * @mbg.generated Wed Jul 12 19:44:04 JST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.EMAIL
     *
     * @param email the value for CUSTOMER.EMAIL
     *
     * @mbg.generated Wed Jul 12 19:44:04 JST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.MEMBERSHIP_TYPE
     *
     * @return the value of CUSTOMER.MEMBERSHIP_TYPE
     *
     * @mbg.generated Wed Jul 12 19:44:04 JST 2017
     */
    public String getMembershipType() {
        return membershipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.MEMBERSHIP_TYPE
     *
     * @param membershipType the value for CUSTOMER.MEMBERSHIP_TYPE
     *
     * @mbg.generated Wed Jul 12 19:44:04 JST 2017
     */
    public void setMembershipType(String membershipType) {
        this.membershipType = membershipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.GRADUATE
     *
     * @return the value of CUSTOMER.GRADUATE
     *
     * @mbg.generated Wed Jul 12 19:44:04 JST 2017
     */
    public String getGraduate() {
        return graduate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.GRADUATE
     *
     * @param graduate the value for CUSTOMER.GRADUATE
     *
     * @mbg.generated Wed Jul 12 19:44:04 JST 2017
     */
    public void setGraduate(String graduate) {
        this.graduate = graduate;
    }
}