INSERT INTO sample.CUSTOMER(NAME,ADDRESS,EMAIL,MEMBERSHIP_TYPE,GRADUATE) VALUES('太郎', '東京都新宿区', 'taro@aa.bb.cc', '1', '1');
INSERT INTO sample.CUSTOMER(NAME,ADDRESS,EMAIL,MEMBERSHIP_TYPE,GRADUATE) VALUES('ジロー', '東京都豊島区', 'jiro@aa.bb.cc', '1', '2');
INSERT INTO sample.CUSTOMER(NAME,ADDRESS,EMAIL,MEMBERSHIP_TYPE,GRADUATE) VALUES('三郎', '長野県松本市', 'sabu@aa.bb.cc', '2', '1');
INSERT INTO sample.CUSTOMER(NAME,ADDRESS,EMAIL,MEMBERSHIP_TYPE,GRADUATE) VALUES('四郎', '東京都足立区', 'siro@aa.bb.cc', '2', '1');
INSERT INTO sample.CUSTOMER(NAME,ADDRESS,EMAIL,MEMBERSHIP_TYPE,GRADUATE) VALUES('ゴロー', '山梨県甲府市', 'goro@aa.bb.cc', '2', '2');
INSERT INTO sample.CUSTOMER(NAME,ADDRESS,EMAIL,MEMBERSHIP_TYPE,GRADUATE) VALUES('花子', '福島県郡山市', 'hanako@aa.bb.cc', '1', '1');
INSERT INTO sample.CUSTOMER(NAME,ADDRESS,EMAIL,MEMBERSHIP_TYPE,GRADUATE) VALUES('美子', '北海道登別市', 'yoshiko@aa.bb.cc', '2', '1');
INSERT INTO sample.CUSTOMER(NAME,ADDRESS,EMAIL,MEMBERSHIP_TYPE,GRADUATE) VALUES('ナオミ', '沖縄県那覇市', 'sabu@aa.bb.cc', '1', '2');